MvcPL/Controllers/BidController.cs
using BLL.Interface.Entities;
using BLL.Interface.Services;
using MvcPL.Models.Bid;
using MvcPL.Infrastructure.Mappers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcPL.Controllers
{
    public class BidController : Controller
    {
        private IService<BllBid> bidService;
        private ILotService lotService;
        private IUserService userService;
        
        public BidController(IService<BllBid> bidService, ILotService lotService, IUserService userService)
        {
            this.bidService = bidService;
            this.lotService = lotService;
            this.userService = userService;
        }

        /*
        public ActionResult Index(int lotId)
        {
            if (lotService.GetById(lotId) == null)
            {
                return HttpNotFound();
            }
            IEnumerable<BidViewModel> bids = bidService
                .GetByPredicate(b => b.LotId == lotId)
                .Select(b => new BidViewModel() 
                {
                    Sum = b.Sum,
                    DateTime = b.DateTime,
                    Lot = lotService.GetById(b.LotId).ToLotViewModel(),
                    User = userService.GetById(b.UserId).ToUserViewModel()
                });
            return View(bids);
        }
         * */

        public ActionResult Lot(int lotId)
        {
            if (lotService.GetById(lotId) == null)
            {
                return HttpNotFound();
            }
            IEnumerable<BidViewModel> bids = bidService
                .GetByPredicate(b => b.LotId == lotId)
                .Select(b => new BidViewModel()
                {
                    Sum = b.Sum,
                    DateTime = b.DateTime,
                    Lot = lotService.GetById(b.LotId).ToLotViewModel(),
                    User = userService.GetById(b.UserId).ToUserViewModel()
                });
            return View("Index", bids);
        }

        [Authorize(Roles = "User")]
        public ActionResult My()
        {
            BllUser bllUser = userService.GetByPredicate(u => u.Email == User.Identity.Name).FirstOrDefault();
            if (bllUser == null)
            {
                return HttpNotFound();
            }
            IEnumerable<BidViewModel> bids = bidService
                .GetByPredicate(b => b.UserId == bllUser.Id)
                .Select(b => new BidViewModel()
                {
                    Sum = b.Sum,
                    DateTime = b.DateTime,
                    Lot = lotService.GetById(b.LotId).ToLotViewModel(),
                    User = userService.GetById(b.UserId).ToUserViewModel()
                });
            return View("Index", bids);
        }

        [HttpPost]
        [Authorize(Roles = "User")]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(int id, int newBid)
        {
            BllLot bllLot = lotService.GetById(id);

            if (bllLot == null)
            {
                return HttpNotFound();
            }

            //Переделать условие, чтобы проверялось не первая ли это ставка
            if (newBid <= bllLot.CurrentPrice)
            {
                // Заменить на ошибку
                return HttpNotFound();
            }

            BllUser bllUser = userService.GetByPredicate(u => u.Email == HttpContext.User.Identity.Name).FirstOrDefault();

            if (bllUser == null)
            {
                ModelState.AddModelError(string.Empty, "Cannot create new bid");
            }
            else if (bllLot.OwnerId == bllUser.Id)
            {
                ModelState.AddModelError(string.Empty, "You Cannot create bid for your lot");
            }
            else if (bllLot.FinishDateTime < DateTime.Now)
            {
                ModelState.AddModelError(string.Empty, "Time is finished");
            }
            else
            {
                BllBid bllBid = new BllBid
                {
                    LotId = bllLot.Id,
                    UserId = bllUser.Id,
                    Sum = newBid,
                    DateTime = DateTime.Now
                };
                bidService.Create(bllBid);
                return RedirectToAction("Details", "Lot", new { id = bllBid.LotId });
            }
            return HttpNotFound();
            /*


            BidCreateModel bidCreate = new BidCreateModel()
            {
                Sum = bllLot.CurrentPrice,
                LotId = id
            };

            return View(bidCreate);
             * */
        }
        /*
        [HttpPost]
        [Authorize(Roles = "User")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BidCreateModel bid)
        {
            if (ModelState.IsValid)
            {
                BllLot bllLot = lotService.Get(bid.LotId);

                if (bid.Sum > bllLot.CurrentPrice)
                {
                    BllUser bllUser = userService.Get(u => u.Email == HttpContext.User.Identity.Name).FirstOrDefault();

                    if (bllUser == null)
                    {
                        ModelState.AddModelError(string.Empty, "Cannot create new bid");
                    }
                    else if (bllLot.FinishDateTime < DateTime.Now)
                    {
                        ModelState.AddModelError(string.Empty, "Time is finished");
                    }
                    else
                    {
                        BllBid bllBid = bid.ToBllBid();
                        bllBid.UserId = bllUser.Id;
                        bidService.Create(bllBid);
                        return RedirectToAction("Details", "Lot", new { id = bllBid.LotId });
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "You should to set greater sum");
                }
            }

            return View(bid);
        }
        */
    }
}

MvcPL/Controllers/CategoryController.cs
using BLL.Interface.Entities;
using BLL.Interface.Services;
using MvcPL.Models.Category;
using MvcPL.Infrastructure.Mappers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcPL.Controllers
{
    //[Authorize(Roles = "Administrator")]
    public class CategoryController : Controller
    {

        private IService<BllCategory> categoryService;
        // Вынести в метод Delete
        private ILotService lotService;

        public CategoryController(IService<BllCategory> categoryService, ILotService lotService)
        {
            this.categoryService = categoryService;
            this.lotService = lotService;
        }


        [Authorize(Roles = "Administrator")]
        public ActionResult Index()
        {
            return View(categoryService.GetAll().Select(c => c.ToCategoryViewModel()));
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create(CategoryCreateModel category)
        {
            if (ModelState.IsValid)
            {
                categoryService.Create(category.ToBllCategory());
                RedirectToAction("Index");
            }
            return View(category);
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            BllCategory toEdit = categoryService.GetById(id);
            if (toEdit == null)
            {
                return HttpNotFound();
            }
            return View(toEdit.ToCategoryEditModel());
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id, CategoryEditModel category)
        {
            if (ModelState.IsValid)
            {
                BllCategory toEdit = categoryService.GetById(id);
                if (toEdit == null)
                    return HttpNotFound();
                BllCategory categoryName = categoryService.GetByPredicate(c => c.Name == category.Name).FirstOrDefault();
                if (categoryName != null && categoryName.Id != toEdit.Id)
                    return HttpNotFound();
                toEdit.Name = category.Name;
                categoryService.Update(toEdit);
                return RedirectToAction("Index");
            }
            return View(category);
        }

        //[HttpGet, HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id)
        {
            BllCategory toDelete = categoryService.GetById(id);
            if (toDelete == null)
                return HttpNotFound();
            if (Request.HttpMethod.ToUpper() == "GET")
                return View(toDelete.ToCategoryViewModel());
            // Вынести удаление лотов в логику сервиса Категорий?
            IEnumerable<BllLot> categoryLots = lotService.GetByPredicate(l => l.CategoryId == toDelete.Id).ToList();
            foreach(var lot in categoryLots)
            {
                lotService.Delete(lot);
            }
            categoryService.Delete(toDelete);
            //return View("Index");
            return RedirectToAction("Index");
        }


        public ActionResult ShowCategories()
        {
            IEnumerable<CategoryViewModel> list = categoryService.GetAll().Select(c => c.ToCategoryViewModel());
            return PartialView("_ListCategories", list);
        }

    }
}

MvcPL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link type="text/css" rel="stylesheet" href="~/Content/bootstrap/3.3.2/css/bootstrap.min.css" />
    <link type="text/css" rel="stylesheet" href="~/Content/bootstrap/3.3.2/css/bootstrap-theme.min.css" />
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div id="container" class="col-md-8 col-md-offset-2" >
        <header>
            <div class="logo">
                <span>My Auction</span>
            </div>
            
            @using (Html.BeginForm("Search", "Lot", FormMethod.Get, new { id = "search-top", @class = "search_form", name = "search_form" }))
            {
                @Html.TextBox("searchString", "",new { Class = "search-string", maxlength = "255", placeholder = "Введите название лота"});
                <input class="search_button" type="submit" value="Найти" />
            }
        </header>
        
        <main id="middle-content" >
            <div id="mn-layout__inner" class="row">
                <nav class="col-md-3">
                    @Html.Partial("_Menu")
                </nav>
                <div class="col-md-9">
                    @RenderBody()
                </div>
            </div>
        </main>

    </div>
    
    
    <footer>
        <span>My Auction &copy; 2015</span>
    </footer>
        

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

MvcPL/Views/Shared/_ListCategories.cshtml
@using MvcPL.Models.Category;
@model IEnumerable<CategoryViewModel>

@foreach (var category in Model)
{
    @Html.ActionLink(category.Name, "Search", "Lot", new { categoryId = category.Id }, new { @class = "list-group-item" })
}

MvcPL/Views/Shared/_Menu.cshtml
<div class="list-group">
    <h4 class="menu_title">Меню</h4>
    @Html.ActionLink("Домашняя", "Index", "Home", null, new { @class = "list-group-item" })
    @if (HttpContext.Current.User.Identity.IsAuthenticated)
    {
        if (HttpContext.Current.User.IsInRole("Moderator"))
        {
            @Html.ActionLink("Не модерированные лоты", "Unmoderated", "Lot", null, new { @class = "list-group-item" })
            @Html.ActionLink("Недавно модерированные", "RecentlyModerated", "Lot", null, new { @class = "list-group-item" })
        }
        if (HttpContext.Current.User.IsInRole("User"))            
        {
            @Html.ActionLink("Личные данные", "Private", "User", null, new { @class = "list-group-item" })
            @Html.ActionLink("Мои лоты", "My", "Lot", null, new { @class = "list-group-item" })
            @Html.ActionLink("Мои ставки", "My", "Bid", null, new { @class = "list-group-item" })
        }
        if (HttpContext.Current.User.IsInRole("Administrator"))
        {
            @Html.ActionLink("Пользователи", "Index", "User", null, new { @class = "list-group-item" })
            @Html.ActionLink("Категории", "Index", "Category", null, new { @class = "list-group-item" })
        }
        @Html.ActionLink("Выйти", "Logout", "User", null, new { @class = "list-group-item" })
    }
    else
    {
        @Html.ActionLink("Войти", "Login", "User", null, new { @class = "list-group-item" })
        @Html.ActionLink("Регистрация", "Create", "User", null, new { @class = "list-group-item" })
    }
    <h4 class="menu_title">Категории</h4>
    @Html.Action("ShowCategories", "Category")
</div> 